"""The Commander's Brief — every finding in language a non-technical CO can act on.

Two outputs per finding: a one-paragraph plain-English summary, and a formal brief in JSSD
service-writing style (decimal paragraph numbering, the layout the Services actually consume). A
cyber tool that outputs a proper staff paper is a quiet show-stopper for this jury. An optional
Hindi rendering of the headline line is included as a stub the operator can fill from the bundled
glossary; the English brief is always produced.

Everything here is drawn from the record — the facts come from the evidence, not the model — so the
brief can never claim more than the gate proved.
"""

from __future__ import annotations

from .finding import Finding, RoeLevel, Status
from .replay import one_line

_SEVERITY_WORD = {"critical": "CRITICAL", "high": "HIGH", "medium": "MODERATE", "low": "LOW"}

# Minimal Hindi headline rendering for the common states (stub; the full product uses the glossary).
_HINDI = {
    Status.VERIFIED: "सुभेद्यता की पुष्टि, सुधार प्रमाणित।",
    Status.REPORT_ONLY: "सुभेद्यता की पुष्टि; सुधार प्रमाणित नहीं — मानव समीक्षा हेतु।",
    Status.CONFIRMED: "सुभेद्यता की पुष्टि।",
}


def plain_summary(f: Finding) -> str:
    """One paragraph a CO can act on."""
    what = one_line(f.message).rstrip(".")
    where = one_line(f.target)
    if f.status is Status.VERIFIED:
        action = ("A fix has been written and proven: the original attack no longer works and no "
                  "other behaviour changed. It is ready to deploy, with a one-command rollback.")
    elif f.status is Status.REPORT_ONLY:
        action = ("The weakness is proven real, but no automatic fix could be proven safe, so none "
                  "was applied. It is referred for expert remediation rather than auto-patched.")
    else:
        action = "The weakness is proven real and a fix is being prepared."
    return (f"A {_SEVERITY_WORD.get(f.severity.lower(), f.severity.upper())} security weakness "
            f"({f.bug_class}) was found in {where}: {what}. {action}")


def jssd_brief(f: Finding, *, serial: int = 1, hindi: bool = False) -> str:
    """A formal brief in JSSD service-writing style: decimal paragraph numbering, service layout."""
    sev = _SEVERITY_WORD.get(f.severity.lower(), f.severity.upper())
    site = f.fix_site_set[0] if f.fix_site_set else None
    where = one_line(f"{site.uri}:{site.start_line}" if site and site.start_line else (site.uri if site else f.target))
    evidence = (f.reproducer.kind.replace("-", " ") if f.reproducer else "none")

    lines = [
        "RESTRICTED",
        "",
        "CYBER SECURITY FINDING — COMMANDER'S BRIEF",
        f"Serial No {serial:03d}",
        "",
        f"1.   Subject.  {sev} vulnerability ({f.bug_class}) identified by RAKSHA AI in the asset "
        f"'{one_line(f.target)}'.",
        "",
        "2.   Situation.",
        f"     2.1   Nature.  {one_line(f.message, 600)}",
        f"     2.2   Location.  {where}.",
        f"     2.3   Evidence.  Confirmed by {evidence}; a reproducer is held in the signed evidence "
        f"bundle and may be replayed on demand.",
        "",
        "3.   Action taken.",
    ]
    if f.status is Status.VERIFIED:
        lines += [
            "     3.1   A corrective patch has been generated and PROVEN against the five-check gate: "
            "the original attack no longer triggers, no other observed behaviour changed, and a fresh "
            "fuzzing pass on the patched build found nothing further.",
            "     3.2   The patch is staged with a one-command rollback"
            + (" and a permanent regression test." if f.regression_test else "."),
            f"     3.3   Authority for deployment is governed by the Rules of Engagement in force for "
            f"this asset (ROE {f.roe_level.value}).",
        ]
        reco = _verified_recommendation(f.roe_level)
    elif f.status is Status.REPORT_ONLY:
        lines += [
            "     3.1   The vulnerability is PROVEN real, but no proposed patch cleared the five-check "
            "gate. In accordance with the fail-closed principle, no unproven fix was applied.",
            "     3.2   The proven vulnerability report is held for expert remediation.",
        ]
        reco = "Detail a cleared software authority to remediate; do not auto-patch."
    else:
        lines += ["     3.1   The vulnerability is proven real; corrective action is in preparation."]
        reco = "Await the corrective patch and its proof before deployment."

    lines += ["", f"4.   Recommendation.  {reco}", "",
              "5.   Attachments.  Signed evidence bundle (reproducer, before/after, gate results, "
              "diff, regression test, rollback).", ""]
    if hindi:
        lines += [f"6.   सारांश.  {_HINDI.get(f.status, 'सुभेद्यता पाई गई।')}", ""]
    lines += ["(Generated by RAKSHA AI. Facts drawn from the signed evidence bundle.)", "RESTRICTED"]
    return "\n".join(lines)


def _verified_recommendation(roe: RoeLevel) -> str:
    """What the CO is asked to do with a proven patch, consistent with the authority in force."""
    if roe in (RoeLevel.R0, RoeLevel.R1):
        return (f"Direct the asset's software authority to apply the proven patch through its change "
                f"process (ROE {roe.value}: the system recommends; it does not apply).")
    if roe is RoeLevel.R2:
        return "Approve deployment of the proven patch (ROE R2: staged, awaiting sign-off)."
    return "Note autonomous deployment of the proven patch under standing orders (ROE R3)."
